package com.silbury.model.evo;

import com.silbury.model.evo.common.EmployeesEO_VIEW;

import java.util.ArrayList;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.Entity;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 23 16:24:24 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesEO_VIEWImpl extends ViewObjectImpl implements EmployeesEO_VIEW {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesEO_VIEWImpl() {
    }
    public void executeValue(String empid){
        try{

            this.setWhereClause("EmployeesENTITYOBJECT.EMPLOYEE_ID = '"+empid+"'");
            this.executeQuery();
            
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    public ArrayList CloneValue(String empid){
        ArrayList empList = new ArrayList();
        try{
            ViewObject vo = this.getViewObject();
            Row createRow = vo.createRow();
          //  createRow.setAttribute("arg0", arg1);


        }catch(Exception ex){
            ex.printStackTrace();
        }
        return empList;
    } 

}

