package com.silbury.model.evo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 23 16:24:24 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesEO_VIEWRowImpl extends ViewRowImpl {


    public static final int ENTITY_EMPLOYEESENTITYOBJECT = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        EmployeeId,
        FirstName,
        LastName,
        Email,
        PhoneNumber,
        HireDate,
        JobId,
        Salary,
        CommissionPct,
        ManagerId,
        DepartmentId,
        JobTitle,
        DepartmentName,
        ManagerFirstName,
        ManagerLastName,
        EmployeesEO_VIEW,
        EmpValuesInserEOView,
        EmployeesEO_VIEW1,
        DepartmentsView1,
        JobsView1,
        Department_LOV1,
        Manager_LOV1,
        ManagerListVO1;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int PHONENUMBER = AttributesEnum.PhoneNumber.index();
    public static final int HIREDATE = AttributesEnum.HireDate.index();
    public static final int JOBID = AttributesEnum.JobId.index();
    public static final int SALARY = AttributesEnum.Salary.index();
    public static final int COMMISSIONPCT = AttributesEnum.CommissionPct.index();
    public static final int MANAGERID = AttributesEnum.ManagerId.index();
    public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();
    public static final int JOBTITLE = AttributesEnum.JobTitle.index();
    public static final int DEPARTMENTNAME = AttributesEnum.DepartmentName.index();
    public static final int MANAGERFIRSTNAME = AttributesEnum.ManagerFirstName.index();
    public static final int MANAGERLASTNAME = AttributesEnum.ManagerLastName.index();
    public static final int EMPLOYEESEO_VIEW = AttributesEnum.EmployeesEO_VIEW.index();
    public static final int EMPVALUESINSEREOVIEW = AttributesEnum.EmpValuesInserEOView.index();
    public static final int EMPLOYEESEO_VIEW1 = AttributesEnum.EmployeesEO_VIEW1.index();
    public static final int DEPARTMENTSVIEW1 = AttributesEnum.DepartmentsView1.index();
    public static final int JOBSVIEW1 = AttributesEnum.JobsView1.index();
    public static final int DEPARTMENT_LOV1 = AttributesEnum.Department_LOV1.index();
    public static final int MANAGER_LOV1 = AttributesEnum.Manager_LOV1.index();
    public static final int MANAGERLISTVO1 = AttributesEnum.ManagerListVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesEO_VIEWRowImpl() {
    }
}

