package com.silbury.model.evo;

import com.silbury.model.evo.common.EmpValuesInserEOView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 10 15:16:04 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpValuesInserEOViewImpl extends ViewObjectImpl implements EmpValuesInserEOView {
    /**
     * This is the default constructor (do not remove).
     */
    public EmpValuesInserEOViewImpl() {
    }
    
    public void executeValue(String empid){
        try{

            this.setWhereClause("EMPLOYEE_ID = '"+empid+"'");
            this.executeQuery();
            
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }

   
}

