package com.silbury.model.eo;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 08 19:32:40 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpValuesInserEODefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmpValuesInserEODefImpl() {
    }
}

