package com.silbury.model.eo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Apr 08 19:29:46 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpValuesInserEOImpl extends EntityImpl {
   

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        EmployeeId,
        FirstName,
        LastName,
        Email,
        PhoneNumber,
        HireDate,
        JobId,
        Salary,
        CommissionPct,
        ManagerId,
        DepartmentId,
        EmployeesEO22,
        EmployeesENTITYOBJECT,
        JobHistory,
        EmployeesEO,
        DepartmentsEO22,
        DepartmentsEO221,
        EmployeesEO_Up,
        Departments,
        Employees,
        DepartmentsEO,
        ManagerIdEmpValuesInserEO,
        EmpValuesInserEO,
        Jobs,
        JobsEOL,
        DepartmentsEO222,
        Departments1,
        DepartmentsEO1,
        EmployeesEO221,
        EmployeesENTITYOBJECT1,
        EmployeesEO1,
        EmployeesEO_Up1,
        Employees1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int PHONENUMBER = AttributesEnum.PhoneNumber.index();
    public static final int HIREDATE = AttributesEnum.HireDate.index();
    public static final int JOBID = AttributesEnum.JobId.index();
    public static final int SALARY = AttributesEnum.Salary.index();
    public static final int COMMISSIONPCT = AttributesEnum.CommissionPct.index();
    public static final int MANAGERID = AttributesEnum.ManagerId.index();
    public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();
    public static final int EMPLOYEESEO22 = AttributesEnum.EmployeesEO22.index();
    public static final int EMPLOYEESENTITYOBJECT = AttributesEnum.EmployeesENTITYOBJECT.index();
    public static final int JOBHISTORY = AttributesEnum.JobHistory.index();
    public static final int EMPLOYEESEO = AttributesEnum.EmployeesEO.index();
    public static final int DEPARTMENTSEO22 = AttributesEnum.DepartmentsEO22.index();
    public static final int DEPARTMENTSEO221 = AttributesEnum.DepartmentsEO221.index();
    public static final int EMPLOYEESEO_UP = AttributesEnum.EmployeesEO_Up.index();
    public static final int DEPARTMENTS = AttributesEnum.Departments.index();
    public static final int EMPLOYEES = AttributesEnum.Employees.index();
    public static final int DEPARTMENTSEO = AttributesEnum.DepartmentsEO.index();
    public static final int MANAGERIDEMPVALUESINSEREO = AttributesEnum.ManagerIdEmpValuesInserEO.index();
    public static final int EMPVALUESINSEREO = AttributesEnum.EmpValuesInserEO.index();
    public static final int JOBS = AttributesEnum.Jobs.index();
    public static final int JOBSEOL = AttributesEnum.JobsEOL.index();
    public static final int DEPARTMENTSEO222 = AttributesEnum.DepartmentsEO222.index();
    public static final int DEPARTMENTS1 = AttributesEnum.Departments1.index();
    public static final int DEPARTMENTSEO1 = AttributesEnum.DepartmentsEO1.index();
    public static final int EMPLOYEESEO221 = AttributesEnum.EmployeesEO221.index();
    public static final int EMPLOYEESENTITYOBJECT1 = AttributesEnum.EmployeesENTITYOBJECT1.index();
    public static final int EMPLOYEESEO1 = AttributesEnum.EmployeesEO1.index();
    public static final int EMPLOYEESEO_UP1 = AttributesEnum.EmployeesEO_Up1.index();
    public static final int EMPLOYEES1 = AttributesEnum.Employees1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EmpValuesInserEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.silbury.model.eo.EmpValuesInserEO");
    }

    /**
     * Gets the attribute value for EmployeeId, using the alias name EmployeeId.
     * @return the value of EmployeeId
     */
    public Number getEmployeeId() {
        return (Number) getAttributeInternal(EMPLOYEEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmployeeId.
     * @param value value to set the EmployeeId
     */
    public void setEmployeeId(Number value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**
     * Gets the attribute value for FirstName, using the alias name FirstName.
     * @return the value of FirstName
     */
    public String getFirstName() {
        return (String) getAttributeInternal(FIRSTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for FirstName.
     * @param value value to set the FirstName
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**
     * Gets the attribute value for LastName, using the alias name LastName.
     * @return the value of LastName
     */
    public String getLastName() {
        return (String) getAttributeInternal(LASTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastName.
     * @param value value to set the LastName
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**
     * Gets the attribute value for Email, using the alias name Email.
     * @return the value of Email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Email.
     * @param value value to set the Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for PhoneNumber, using the alias name PhoneNumber.
     * @return the value of PhoneNumber
     */
    public String getPhoneNumber() {
        return (String) getAttributeInternal(PHONENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for PhoneNumber.
     * @param value value to set the PhoneNumber
     */
    public void setPhoneNumber(String value) {
        setAttributeInternal(PHONENUMBER, value);
    }

    /**
     * Gets the attribute value for HireDate, using the alias name HireDate.
     * @return the value of HireDate
     */
    public Timestamp getHireDate() {
        return (Timestamp) getAttributeInternal(HIREDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for HireDate.
     * @param value value to set the HireDate
     */
    public void setHireDate(Timestamp value) {
        setAttributeInternal(HIREDATE, value);
    }

    /**
     * Gets the attribute value for JobId, using the alias name JobId.
     * @return the value of JobId
     */
    public String getJobId() {
        return (String) getAttributeInternal(JOBID);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobId.
     * @param value value to set the JobId
     */
    public void setJobId(String value) {
        setAttributeInternal(JOBID, value);
    }

    /**
     * Gets the attribute value for Salary, using the alias name Salary.
     * @return the value of Salary
     */
    public BigDecimal getSalary() {
        return (BigDecimal) getAttributeInternal(SALARY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Salary.
     * @param value value to set the Salary
     */
    public void setSalary(BigDecimal value) {
        setAttributeInternal(SALARY, value);
    }

    /**
     * Gets the attribute value for CommissionPct, using the alias name CommissionPct.
     * @return the value of CommissionPct
     */
    public BigDecimal getCommissionPct() {
        return (BigDecimal) getAttributeInternal(COMMISSIONPCT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommissionPct.
     * @param value value to set the CommissionPct
     */
    public void setCommissionPct(BigDecimal value) {
        setAttributeInternal(COMMISSIONPCT, value);
    }

    /**
     * Gets the attribute value for ManagerId, using the alias name ManagerId.
     * @return the value of ManagerId
     */
    public Integer getManagerId() {
        return (Integer) getAttributeInternal(MANAGERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ManagerId.
     * @param value value to set the ManagerId
     */
    public void setManagerId(Integer value) {
        setAttributeInternal(MANAGERID, value);
    }

    /**
     * Gets the attribute value for DepartmentId, using the alias name DepartmentId.
     * @return the value of DepartmentId
     */
    public Integer getDepartmentId() {
        return (Integer) getAttributeInternal(DEPARTMENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DepartmentId.
     * @param value value to set the DepartmentId
     */
    public void setDepartmentId(Integer value) {
        setAttributeInternal(DEPARTMENTID, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getEmployeesEO22() {
        return (RowIterator) getAttributeInternal(EMPLOYEESEO22);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getEmployeesENTITYOBJECT() {
        return (RowIterator) getAttributeInternal(EMPLOYEESENTITYOBJECT);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getJobHistory() {
        return (RowIterator) getAttributeInternal(JOBHISTORY);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getEmployeesEO() {
        return (RowIterator) getAttributeInternal(EMPLOYEESEO);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getDepartmentsEO22() {
        return (RowIterator) getAttributeInternal(DEPARTMENTSEO22);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getDepartmentsEO221() {
        return (RowIterator) getAttributeInternal(DEPARTMENTSEO221);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getEmployeesEO_Up() {
        return (RowIterator) getAttributeInternal(EMPLOYEESEO_UP);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getDepartments() {
        return (RowIterator) getAttributeInternal(DEPARTMENTS);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getEmployees() {
        return (RowIterator) getAttributeInternal(EMPLOYEES);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getDepartmentsEO() {
        return (RowIterator) getAttributeInternal(DEPARTMENTSEO);
    }

    /**
     * @return the associated entity EmpValuesInserEOImpl.
     */
    public EmpValuesInserEOImpl getManagerIdEmpValuesInserEO() {
        return (EmpValuesInserEOImpl) getAttributeInternal(MANAGERIDEMPVALUESINSEREO);
    }

    /**
     * Sets <code>value</code> as the associated entity EmpValuesInserEOImpl.
     */
    public void setManagerIdEmpValuesInserEO(EmpValuesInserEOImpl value) {
        setAttributeInternal(MANAGERIDEMPVALUESINSEREO, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getEmpValuesInserEO() {
        return (RowIterator) getAttributeInternal(EMPVALUESINSEREO);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getJobs() {
        return (EntityImpl) getAttributeInternal(JOBS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setJobs(EntityImpl value) {
        setAttributeInternal(JOBS, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getJobsEOL() {
        return (EntityImpl) getAttributeInternal(JOBSEOL);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setJobsEOL(EntityImpl value) {
        setAttributeInternal(JOBSEOL, value);
    }

    /**
     * @return the associated entity DepartmentsEO22Impl.
     */
    public DepartmentsEO22Impl getDepartmentsEO222() {
        return (DepartmentsEO22Impl) getAttributeInternal(DEPARTMENTSEO222);
    }

    /**
     * Sets <code>value</code> as the associated entity DepartmentsEO22Impl.
     */
    public void setDepartmentsEO222(DepartmentsEO22Impl value) {
        setAttributeInternal(DEPARTMENTSEO222, value);
    }

    /**
     * @return the associated entity DepartmentsImpl.
     */
    public DepartmentsImpl getDepartments1() {
        return (DepartmentsImpl) getAttributeInternal(DEPARTMENTS1);
    }

    /**
     * Sets <code>value</code> as the associated entity DepartmentsImpl.
     */
    public void setDepartments1(DepartmentsImpl value) {
        setAttributeInternal(DEPARTMENTS1, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getDepartmentsEO1() {
        return (EntityImpl) getAttributeInternal(DEPARTMENTSEO1);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setDepartmentsEO1(EntityImpl value) {
        setAttributeInternal(DEPARTMENTSEO1, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getEmployeesEO221() {
        return (EntityImpl) getAttributeInternal(EMPLOYEESEO221);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setEmployeesEO221(EntityImpl value) {
        setAttributeInternal(EMPLOYEESEO221, value);
    }

    /**
     * @return the associated entity EmployeesENTITYOBJECTImpl.
     */
    public EmployeesENTITYOBJECTImpl getEmployeesENTITYOBJECT1() {
        return (EmployeesENTITYOBJECTImpl) getAttributeInternal(EMPLOYEESENTITYOBJECT1);
    }

    /**
     * Sets <code>value</code> as the associated entity EmployeesENTITYOBJECTImpl.
     */
    public void setEmployeesENTITYOBJECT1(EmployeesENTITYOBJECTImpl value) {
        setAttributeInternal(EMPLOYEESENTITYOBJECT1, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getEmployeesEO1() {
        return (EntityImpl) getAttributeInternal(EMPLOYEESEO1);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setEmployeesEO1(EntityImpl value) {
        setAttributeInternal(EMPLOYEESEO1, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getEmployeesEO_Up1() {
        return (EntityImpl) getAttributeInternal(EMPLOYEESEO_UP1);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setEmployeesEO_Up1(EntityImpl value) {
        setAttributeInternal(EMPLOYEESEO_UP1, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getEmployees1() {
        return (EntityImpl) getAttributeInternal(EMPLOYEES1);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setEmployees1(EntityImpl value) {
        setAttributeInternal(EMPLOYEES1, value);
    }


    /**
     * @param employeeId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number employeeId) {
        return new Key(new Object[] { employeeId });
    }

    @Override
    
    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        setEmployeeId(getNextSequenceVal("EMPLOYEES_SEQ"));
    }
    
    protected Number getNextSequenceVal(String sequenceName){        
        SequenceImpl s = new SequenceImpl(sequenceName, getDBTransaction());
        return s.getSequenceNumber();
    
    }
}

