package com.silbury.model.vo;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 28 13:53:04 IST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeeVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        EmployeeId,
        FirstName,
        LastName,
        JobTitle,
        DepartmentId,
        DepartmentName,
        PhoneNumber,
        PhoneNumber1,
        Email,
        Linkedin,
        Twitter,
        Facebook,
        Google,
        StreetAddress,
        City,
        StateProvince,
        CountryName,
        PostalCode,
        Rating,
        Potential,
        Compratio,
        Salary,
        Bouns,
        CommissionPct,
        ManagerId,
        HireDate,
        MgrFirstNm,
        MgrLastNm;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return EmployeeVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return EmployeeVORowImpl.AttributesEnum.firstIndex() +
                   EmployeeVORowImpl.AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = EmployeeVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int FIRSTNAME = AttributesEnum.FirstName.index();
    public static final int LASTNAME = AttributesEnum.LastName.index();
    public static final int JOBTITLE = AttributesEnum.JobTitle.index();
    public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();
    public static final int DEPARTMENTNAME = AttributesEnum.DepartmentName.index();
    public static final int PHONENUMBER = AttributesEnum.PhoneNumber.index();
    public static final int PHONENUMBER1 = AttributesEnum.PhoneNumber1.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int LINKEDIN = AttributesEnum.Linkedin.index();
    public static final int TWITTER = AttributesEnum.Twitter.index();
    public static final int FACEBOOK = AttributesEnum.Facebook.index();
    public static final int GOOGLE = AttributesEnum.Google.index();
    public static final int STREETADDRESS = AttributesEnum.StreetAddress.index();
    public static final int CITY = AttributesEnum.City.index();
    public static final int STATEPROVINCE = AttributesEnum.StateProvince.index();
    public static final int COUNTRYNAME = AttributesEnum.CountryName.index();
    public static final int POSTALCODE = AttributesEnum.PostalCode.index();
    public static final int RATING = AttributesEnum.Rating.index();
    public static final int POTENTIAL = AttributesEnum.Potential.index();
    public static final int COMPRATIO = AttributesEnum.Compratio.index();
    public static final int SALARY = AttributesEnum.Salary.index();
    public static final int BOUNS = AttributesEnum.Bouns.index();
    public static final int COMMISSIONPCT = AttributesEnum.CommissionPct.index();
    public static final int MANAGERID = AttributesEnum.ManagerId.index();
    public static final int HIREDATE = AttributesEnum.HireDate.index();
    public static final int MGRFIRSTNM = AttributesEnum.MgrFirstNm.index();
    public static final int MGRLASTNM = AttributesEnum.MgrLastNm.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EmployeeVORowImpl() {
    }
}

