package com.silbury.model.evo.common;

import java.util.ArrayList;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 23 16:29:52 IST 2016
// ---------------------------------------------------------------------
public interface EmployeesEO_VIEW extends ViewObject {

    ArrayList CloneValue(String empid);

}

