package com.silbury.model.evo.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 10 15:17:24 IST 2016
// ---------------------------------------------------------------------
public interface EmpValuesInserEOView extends ViewObject {
    void executeValue(String empid);
}

